name: certify_client
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  go_router: ^13.2.0
  get_it: ^7.6.7
  injectable: ^2.4.1
  dio: ^5.9.0
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  logger: ^2.0.2
  local_auth: ^2.1.6
  flutter_secure_storage: ^9.0.0
  mobile_scanner: ^5.0.0
  permission_handler: ^11.3.0
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  injectable_generator: ^2.6.3
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - .env
